name: Generate Translations

on:
    workflow_dispatch:
        inputs:
            file_name:
                description: "Select the file name to generate translations"
                type: choice
                options:
                    - "GameRules"
                    - "Appendix-Features"
                required: true
                default: "GameRules"

jobs:
    translation:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                language:
                    [
                        { code: "EN", name: "English" },
                        { code: "JA", name: "Japanese" },
                        { code: "ES", name: "Spanish" },
                    ]
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v4
              with:
                  ref: main

            - name: Translate to ${{ matrix.language.name }}
              uses: 0xjord4n/aixion@v1.2.1
              id: aixion
              with:
                  config: >
                      {
                        "provider": "openai",
                        "provider_options": {
                          "base_url": "${{ vars.AI_PROVIDER_BASE_URL }}",
                          "api_key": "${{ secrets.AI_PROVIDER_API_KEY }}"
                        },
                        "messages": [
                          {
                            "role": "system",
                            "content": "You will be provided with a markdown file in Chinese, and your task is to translate it into ${{ matrix.language.name }}."
                          },
                          {
                            "role": "user",
                            "content_path": "${{ github.event.inputs.file_name }}.md"
                          }
                        ],
                        "save_path": "i18n/${{ github.event.inputs.file_name }}/${{ github.event.inputs.file_name }}_${{ matrix.language.code }}.md",
                        "model": "${{ vars.AI_MODEL_NAME }}"
                      }

            # Upload each translated file as an artifact
            - name: Upload translation
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ github.event.inputs.file_name }}-${{ matrix.language.code }}
                  path: i18n/${{ github.event.inputs.file_name }}/${{ github.event.inputs.file_name }}_${{ matrix.language.code }}.md

    commit:
        needs: translation
        runs-on: ubuntu-latest

        permissions:
          contents: write

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: main

            # Download all translation artifacts
            - name: Download all translations
              uses: actions/download-artifact@v4
              with:
                  pattern: ${{ github.event.inputs.file_name }}-*
                  path: i18n/${{ github.event.inputs.file_name }}
                  merge-multiple: true

            - name: Commit all translations
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: "chore: update all markdown translations"
                  branch: main
                  file_pattern: "i18n/${{ github.event.inputs.file_name }}/${{ github.event.inputs.file_name }}_*.md"
                  commit_author: "GitHub Action <actions@github.com>"
