name: Merge Content

on:
  push:
    branches:
      - main
    paths:
      - 'Features/**'
      # 可以在这里添加更多目录
      # - 'OtherDir/**'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 获取完整的 git 历史

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Get changed directories
        id: changed-dirs
        run: |
          # 获取所有变更的目录，移除引号并处理输出
          CHANGED_DIRS=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '^[^/]+/' | cut -d'/' -f1 | sort -u | tr -d '"' | tr '\n' ',' | sed 's/,$//')
          echo "Changed directories: $CHANGED_DIRS"
          echo "dirs=$CHANGED_DIRS" >> $GITHUB_OUTPUT

      - name: Execute merge script
        run: |
          if [ -n "${{ steps.changed-dirs.outputs.dirs }}" ]; then
            echo "Processing directories: ${{ steps.changed-dirs.outputs.dirs }}"
            python scripts/merge.py "${{ steps.changed-dirs.outputs.dirs }}"
          else
            echo "No directories to process"
          fi

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Merge content from changed directories"
          file_pattern: "*.md"